-- Product marketplace display fields
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "compareAtPrice" DECIMAL(10,2);
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "brand" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "rating" DECIMAL(2,1) NOT NULL DEFAULT 4.5;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "reviewCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "promoBadge" TEXT;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "deliveryDaysMin" INTEGER;
ALTER TABLE "products" ADD COLUMN IF NOT EXISTS "deliveryDaysMax" INTEGER;
